# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
workspace 'YZOpenSDK'

use_frameworks!

target 'YZBaseDemo' do
  project 'YouzanBaseDemo/YZBaseDemo.xcodeproj'
  
  pod 'YZAppSDK/Core', :path=>'../Release'
  pod 'YZAppSDK/Base', :path=>'../Release'

end
