# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
workspace 'YZOpenSDK'

target 'YZBaseDemo' do
  project 'YouzanBaseDemo/YZBaseDemo.xcodeproj'
  
  pod 'YZAppSDK', :podspec => '../YZAppSDK.podspec'

end